
var str='<ul id="cssmenu1">';


     str+='<li style="border-left: 1px solid #FFFFCC;"><a href="#">&nbsp;&nbsp;Dressuur</a>';
         str+='<ul>';
	     str+='<li><a    href="algemeen/op-afstijgen-paard.html" target="_parent">op- afstijgen</a></li>';
	     str+='<li><a    href="dressuur/basis.html" target="_parent">basis dressuur</a></li>';
	     str+='<li><a    href="dressuur/rijbaanfiguren.html" target="_parent">rijbaanfiguren</a></li>';
	     str+='<li><a    href="dressuur/rijbaanfiguren-rijden.html" target="_parent">rijbaanfiguren rijden</a></li>';
	     str+='<li><a    href="dressuur/gangen-stap.html"  target="_parent">stap</a>';
	     str+='<li><a    href="dressuur/gangen-draf.html"  target="_parent">draf</a>';
	     str+='<li><a    href="dressuur/gangen-galop.html"  target="_parent">galop</a>';
	     str+='<li><a    href="dressuur/zithouding.html"  target="_parent">zithouding</a></li>';
	     str+='<li><a    href="dressuur/hulpen.html" target="_parent">hulpen</a></li>';
	     str+='<li><a    href="dressuur/overgangen.html"  target="_parent">overgangen</a></li>';
	     str+='<li><a    href="dressuur/stelling-buiging.html"  target="_parent">stelling/buiging</a></li>';
	     str+='<li><a    href="dressuur/rechtrichten.html"  target="_parent">rechtrichten</a></li>';
	     str+='<li><a    href="dressuur/aanleuning.html"  target="_parent">aan de teugel</a></li>';
	     str+='<li><a    href="dressuur/voorwaarts-neerwaarts.html"  target="_parent">voorw.-neerwaarts</a></li>';
	     str+='<li><a    href="dressuur/zijgangen.html"  target="_parent">zijgangen</a></li>';
	     str+='<li><a    href="dressuur/dubbel-bit.html"  target="_parent">dubbel bit</a></li>';
	     str+='<li><a    href="dressuur/galopchangementen.html"  target="_parent">galopchangementen</a></li>';
	     str+='<li><a    href="dressuur/hogeschool.html" target="_parent">hogeschool</a></li>';
	     str+='<li><a    href="dressuur/diversen.html"  target="_parent">diversen</a></li>';
	     str+='<li><a    href="dressuur/cavaletti-oefeningen-dressuur.html"  target="_parent">cavaletti oefeningen</a></li>';
	     str+='<li><a    href="dressuur/dressuuroefeningen-1.html"  target="_parent">dressuuroefeningen</a></li>';
	     str+='<li><a    href="dressuur/eerste-wedstrijd.html" target="_parent">je eerste wedstrijd</a></li>';
         str+='</ul>';
     str+='</li>';
     str+='<li><a href="#">&nbsp;&nbsp;Springen</a>';
         str+='<ul>';
	     str+='<li><a href="springen/springpaard.html"  target="_parent">het springpaard</a></li>';
	     str+='<li><a href="springen/hindernissen.html"  target="_parent">hindernissen</a></li>';
	     str+='<li><a href="springen/afstanden.html"  target="_parent">afstanden</a></li>';
	     str+='<li><a href="springen/vrij-springen.html"  target="_parent">vrij springen</a></li>';
	     str+='<li><a href="algemeen/op-afstijgen-paard.html" target="_parent">op- afstijgen</a></li>';
	     str+='<li><a href="springen/zithouding-springen.html"  target="_parent">zithouding springen</a></li>';
	     str+='<li><a    href="springen/leren-springen-paard.html"  target="_parent">paard leren springen</a></li>';
	     str+='<li><a href="springen/cavaletti-oefeningen.html"  target="_parent">cavaletti/balken</a></li>';
	     str+='<li><a href="#">springoefeningen</a>';
 	    	 str+=' <ul>';
 	   	 str+='<li><a href="springen/springoefeningen.html">basisoefeningen</a></li>';
	   	 str+='<li><a href="springen/springoefeningen-3.html">gevorderden</a></li>';
		 str+='</ul>';
  		 str+='</li>';
	     str+='<li><a href="springen/springlijntjes.html"  target="_parent">springlijntjes</a></li>';
	     str+='<li><a href="springen/springtraining.html"  target="_parent">training</a></li>';
	     str+='<li><a href="springen/parcours-rijden.html"  target="_parent">parcours rijden</a></li>';
	     str+='<li><a href="springen/parcours-data.html"  target="_parent">parcours feiten</a></li>';
	     str+='<li><a href="springen/parcoursschetsen.html"  target="_parent">parcoursschetsen</a>';
               str+=' <ul>';
 	   	 str+='<li><a href="springen/parcoursschetsen20x40.html">20x40</a></li>';
		 str+='<li><a href="springen/parcoursschetsen30x60.html">30x60</a></li>';
 	   	 str+='<li><a href="springen/parcoursschetsen20x40-weinig-materiaal.html">weinig materiaal</a></li>';
		 str+='<li><a href="springen/parcoursschetsen.html">professioneel</a></li>';
		 str+='</ul>';
  		 str+='</li>';		
	     str+='<li><a href="springen/parcoursen.html" target="_parent">parcoursen soorten</a></li>';
	     str+='<li><a href="springen/barrage-rijden.html"  target="_parent">barrage rijden</a></li>';
	     str+='<li><a href="#">problemen</a>';
 	    	 str+=' <ul>';
 	   	  str+='<li><a href="springen/problemen-weigeren.html">weigeren/uitbreken</a></li>';
 	   	  str+='<li><a href="springen/problemen-gehaast-voor-sprong.html">gehaast voor sprong</a></li>';
	   	  str+='<li><a href="springen/problemen-wegrennen-na-sprong.html">wegrennen na sprong</a></li>';
	   	  str+='<li><a href="springen/problemen-opgewonden-in-parcours.html">heet in parcours</a></li>';
	   	  str+='<li><a href="springen/problemen-ruggebruik.html">ruggegebruik</a></li>';
	   	  str+='<li><a href="springen/problemen-slingeren.html">slingeren</a></li>';
	   	  str+='<li><a href="springen/problemen-scheef-springen.html">scheef springen</a></li>';
		     str+='</ul>';
  		   str+='</li>';
	     str+='<li><a   href="springen/springmateriaal-zelf-maken.html"  target="_parent">materiaal zelf maken</a></li>';
	     str+='<li><a   href="springen/eerste-wedstrijd-springen.html"  target="_parent">eerste springwedstrijd</a></li>';
         str+='</ul>';
     str+='</li>';
     str+='<li><a href="#">&nbsp;&nbsp;Paard</a>';
         str+='<ul>';
	     str+='<li><a href="paard/gangen.html"  target="_parent">gangen</a>';
 	     str+='<li><a href="paard/exterieur.html">exterieur</a></li>';
 	     str+='<li><a href="paard/anatomie.html">anatomie</a>';
 	    	 str+=' <ul>';
	   	 str+='<li><a href="paard/anatomie.html">algemeen</a></li>';
 	   	  str+='<li><a href="paard/skelet.html">skelet</a></li>';
 	    	 str+='<li><a href="paard/spieren.html">spieren/ pezen/ banden</a></li>';
	    	 str+='<li><a href="paard/bloedsomloop.html">bloedsomloop</a></li>';
 	    	 str+=' <li><a href="paard/gebit.html">gebit</a></li>';
	    	 str+='<li><a href="paard/spijsverteringsstelsel.html">spijsvertering</a></li>';
	    	 str+=' </ul>';
	    	 str+=' </li>';
	     str+='<li><a href="paard/gezondheid.html">gezondheid</a></li>';
	     str+='<li><a href="paard/beenstanden.html">beenstanden</a></li>';
 	     str+='<li><a href="paard/kreupelheidsonderzoek.html">kreupelh.onderzoek</a></li>';
	     str+='<li><a href="paard/gewicht.html">gewicht paard/pony</a></li>';

         str+='</ul>';
     str+='</li>';
     str+='<li><a href="#">&nbsp;&nbsp;Verzorging</a>';
         str+='<ul>';
	     str+='<li><a href="verzorging/poetsen.html">poetsen</a></li>';
 	     str+='<li><a href="verzorging/toiletteren-wassen.html">paard wassen</a></li>';
 	     str+='<li><a href="verzorging/toiletteren-manen.html">manen toiletteren</a></li>';
  	     str+='<li><a href="verzorging/toiletteren-staart-hoofd-benen.html">toiletteren</a></li>';

 	     str+='<li><a href="#">voeding</a>';
 	    	 str+=' <ul>';
  	         str+='<li><a href="verzorging/voeding.html">voeding</a></li>';
  	         str+='<li><a href="verzorging/weilandbeheer.html">weilandbeheer</a></li>';
  	         str+='<li><a href="diversen/giftige-planten.html">giftige planten</a></li>';


 	     		str+='<li><a href="#">voedselziekten</a>';
 	    	 		str+=' <ul>';
	   	 		str+='<li><a href="verzorging/voedsel-gerelateerde-ziekten.html">algemeen</a></li>';
 	   	 		str+='<li><a href="ziekten/spijsvertering/koliek.html">koliek</a></li>';
 	   	 		str+='<li><a href="ziekten/spijsvertering/maagzweer.html">maagzweer</a></li>';
 	    	 		str+='<li><a href="ziekten/benen/hoefbevangenheid.html">hoefbevangenheid</a></li>';
 	    	 		str+='<li><a href="ziekten/benen/spierbevangenheid.html">spierbevangenheid</a></li>';
	    	 		str+='</ul>';
	    	 		str+='</li>';
	    	 str+=' </ul>';
	    	 str+=' </li>';
         str+='</ul>';
     str+='</li>';
     str+='<li><a href="#">&nbsp;&nbsp;Uitrusting</a>';
         str+='<ul>';
	     str+='<li><a  href="uitrusting/uitrusting-ruiter.html"  target="_parent">&nbsp;ruiter</a></li>'; 
	     str+='<li><a  href="uitrusting/uitrusting-paard.html"  target="_parent">&nbsp;paard</a></li>';     		
	     str+='<li><a  href="harnachement/zadel.html"  target="_parent">&nbsp;het zadel</a></li>';
	     str+='<li><a  href="harnachement/hoofdstel.html"  target="_parent">&nbsp;hoofdstel/halster</a></li>';
	     str+='<li><a  href="harnachement/bit.html"  target="_parent">&nbsp;het bit</a></li>';
	     str+='<li><a  href="harnachement/teugels.html"  target="_parent">&nbsp;(hulp)teugels</a></li>';	
	     str+='<li><a  href="uitrusting/dekens.html"  target="_parent">&nbsp;dekens</a></li>';
	     str+='<li><a  href="uitrusting/uitrusting-knhs.html"  target="_parent">&nbsp;KNHS voorschriften</a></li>';
     str+='</ul>';
     str+='</li>';
     str+='<li><a href="#">&nbsp;&nbsp;Algemeen</a>';
         str+='<ul>';
    	     str+='<li><a href="algemeen/longeren.html">longeren enkel</a></li>';
	     str+='<li><a href="algemeen/dubbele-longe.html">longeren dubbel</a></li>';
         str+='</ul>';
     str+='</li>';
     str+='<li><a href="#">&nbsp;&nbsp;Vervoer</a>';
         str+='<ul>';
    	     str+='<li><a href="vervoer/trailerladen.html">trailerladen</a></li>';
	     str+='<li><a href="vervoer/trailers.html">trailers</a></li>';
	     str+='<li><a href="vervoer/rijbewijs.html">wat mag ik trekken</a></li>';
	     str+='<li><a href="vervoer/transportverordening.html">transportverordening</a></li>';
         str+='</ul>';
     str+='</li>';
     str+='<li><a href="#">&nbsp;&nbsp;Diversen</a>';
         str+='<ul>';
	     str+='<li><a href="diversen/paardenbegrippen.html">Paardenbegrippen</a></li>';
	     str+='<li><a href="diversen/engels-duits-frans.html">Duits/Frans/Engels</a></li>';
  	         str+='<li><a href="diversen/giftige-planten.html">giftige planten</a></li>';
         str+='</ul>';
     str+='</li>';
     str+='<li><a href="#">&nbsp;&nbsp;Over ons</a>';
         str+='<ul>';
	     str+='<li><a href="over ons/contact.php">contact</a></li>';
	     str+='<li><a href="over ons/gastenboek.html">gastenboek</a></li>';
	     str+='<li><a href="over ons/advertenties.html">advertenties</a></li>';
	     str+='<li><a href="over ons/links.html">links</a></li>';
	     str+='<li><a href="over ons/bronnen.html">bronnen</a></li>';
         str+='</ul>';
    str+='</li>';
	     str+='<li><a href="index.html">&nbsp;&nbsp;Home</a></li>';
     str+='</ul>';
     str+='<br style="clear: left;" />';

document.write(str);
// Add other links a desired